### ISSUE TITLE
incompatible 

### ISSUE THREAD

**Issue by GodReza** [Smootheez/Elytra-Control#2]
![Screenshot 2024-10-12 162205](https://github.com/user-attachments/assets/e1e09554-47c4-40cf-8082-65a84ac4799b)
there wasnt a problem till i updated your mod and i downloaded the dependencies also but still an issue

**Comment by Smootheez** [comment]
you have to use >0.16.5 fabric loader in order to run this mod. what i see is you using 0.16.2 which is <0.16.5. if you still want to use 0.16.2 fabric loader, then you can use old version of this mod. thanks for your patience:)
